export type ThemeId = "default" | "botanical" | "cloudscape" | "shire" | "blush" | "origami" | "viking" | "lavender";

export interface AppThemeColors {
  text: string;
  tint: string;
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  nexusGlow: string;
  updateGlow: string;
  statusRead: string;
  statusReading: string;
  statusUnread: string;
  shelfColor: string;
  shelfHighlight: string;
}

export const THEME_COLORS: Record<ThemeId, AppThemeColors> = {
  default: {
    text: "#f0e6d3",
    tint: "#c084fc",
    background: "#0f0e17",
    foreground: "#fffffe",
    card: "#1a1833",
    cardForeground: "#f0e6d3",
    primary: "#c084fc",
    primaryForeground: "#0f0e17",
    secondary: "#2d2b50",
    secondaryForeground: "#f0e6d3",
    muted: "#1e1d36",
    mutedForeground: "#a7a9be",
    accent: "#f59e0b",
    accentForeground: "#0f0e17",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2d2b50",
    input: "#2d2b50",
    nexusGlow: "#e879f9",
    updateGlow: "#f59e0b",
    statusRead: "#34d399",
    statusReading: "#c084fc",
    statusUnread: "#6b7280",
    shelfColor: "#1e1d36",
    shelfHighlight: "#2d2b50",
  },
  botanical: {
    text: "#2d1f0a",
    tint: "#4a7c40",
    background: "#f4ead5",
    foreground: "#2d1f0a",
    card: "#fffdf4",
    cardForeground: "#2d1f0a",
    primary: "#4a7c40",
    primaryForeground: "#ffffff",
    secondary: "#e0d4b0",
    secondaryForeground: "#2d1f0a",
    muted: "#ede2cc",
    mutedForeground: "#7a5f3a",
    accent: "#d4625a",
    accentForeground: "#ffffff",
    destructive: "#c0392b",
    destructiveForeground: "#ffffff",
    border: "#c8b08a",
    input: "#e0d4b0",
    nexusGlow: "#9b59b6",
    updateGlow: "#d4a853",
    statusRead: "#4a7c40",
    statusReading: "#c4785a",
    statusUnread: "#9a8068",
    shelfColor: "#8B6914",
    shelfHighlight: "#d4a853",
  },
  cloudscape: {
    text: "#ffffff",
    tint: "#ffffff",
    background: "#4A90E2",
    foreground: "#ffffff",
    card: "#dff0ff",
    cardForeground: "#1e3f6f",
    primary: "#ffffff",
    primaryForeground: "#1e3f6f",
    secondary: "#cce4ff",
    secondaryForeground: "#1e3f6f",
    muted: "#7fb6ef",
    mutedForeground: "#eff7ff",
    accent: "#ffb347",
    accentForeground: "#1e3f6f",
    destructive: "#e35d6a",
    destructiveForeground: "#ffffff",
    border: "#dff0ff",
    input: "#dff0ff",
    nexusGlow: "#ffffff",
    updateGlow: "#ffb347",
    statusRead: "#ffffff",
    statusReading: "#fff6a9",
    statusUnread: "#dff0ff",
    shelfColor: "#ffffff",
    shelfHighlight: "#ffb347",
  },
  shire: {
    text: "#f7f3e2",
    tint: "#c4d98a",
    background: "#2d4128",
    foreground: "#f7f3e2",
    card: "#385032",
    cardForeground: "#f7f3e2",
    primary: "#c4d98a",
    primaryForeground: "#24341f",
    secondary: "#4c6142",
    secondaryForeground: "#f7f3e2",
    muted: "#34482f",
    mutedForeground: "#d8cfa7",
    accent: "#d2a35a",
    accentForeground: "#24341f",
    destructive: "#de5c4a",
    destructiveForeground: "#ffffff",
    border: "#66795a",
    input: "#4c6142",
    nexusGlow: "#d6e58f",
    updateGlow: "#d2a35a",
    statusRead: "#c4d98a",
    statusReading: "#d2a35a",
    statusUnread: "#a79d83",
    shelfColor: "#5b4427",
    shelfHighlight: "#d2a35a",
  },
  blush: {
    text: "#6b3550",
    tint: "#e38aa7",
    background: "#fadadd",
    foreground: "#6b3550",
    card: "#fff9fb",
    cardForeground: "#6b3550",
    primary: "#e38aa7",
    primaryForeground: "#ffffff",
    secondary: "#ffe8ef",
    secondaryForeground: "#6b3550",
    muted: "#fbeef2",
    mutedForeground: "#a46b86",
    accent: "#d6b15f",
    accentForeground: "#6b3550",
    destructive: "#d95c7a",
    destructiveForeground: "#ffffff",
    border: "#efc6d1",
    input: "#ffe8ef",
    nexusGlow: "#f5a7c2",
    updateGlow: "#d6b15f",
    statusRead: "#bf6e8d",
    statusReading: "#e38aa7",
    statusUnread: "#b79aa8",
    shelfColor: "#ffffff",
    shelfHighlight: "#d6b15f",
  },
  origami: {
    text: "#2a3050",
    tint: "#5b9bd5",
    background: "#f5f3ee",
    foreground: "#2a3050",
    card: "#ffffff",
    cardForeground: "#2a3050",
    primary: "#5b9bd5",
    primaryForeground: "#ffffff",
    secondary: "#d4ebf9",
    secondaryForeground: "#2a3050",
    muted: "#eef5fc",
    mutedForeground: "#7a90b0",
    accent: "#f5a0c0",
    accentForeground: "#2a3050",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#c0d8f0",
    input: "#d4ebf9",
    nexusGlow: "#9070e0",
    updateGlow: "#f5c040",
    statusRead: "#5bbf9f",
    statusReading: "#5b9bd5",
    statusUnread: "#9aabb5",
    shelfColor: "#5b9bd5",
    shelfHighlight: "#a8d4f5",
  },
  viking: {
    text: "#e7f0f6",
    tint: "#9fc7d6",
    background: "#3A4F5C",
    foreground: "#e7f0f6",
    card: "#435965",
    cardForeground: "#e7f0f6",
    primary: "#9fc7d6",
    primaryForeground: "#20313b",
    secondary: "#5b6c76",
    secondaryForeground: "#e7f0f6",
    muted: "#4f626d",
    mutedForeground: "#c8d4db",
    accent: "#d59e4a",
    accentForeground: "#20313b",
    destructive: "#ff6b5f",
    destructiveForeground: "#ffffff",
    border: "#607580",
    input: "#4f626d",
    nexusGlow: "#9fc7d6",
    updateGlow: "#d59e4a",
    statusRead: "#9fc7d6",
    statusReading: "#d59e4a",
    statusUnread: "#96a6af",
    shelfColor: "#2d1f18",
    shelfHighlight: "#d59e4a",
  },
  lavender: {
    text: "#3F51B5",
    tint: "#7e6ee6",
    background: "#E8EAF6",
    foreground: "#3F51B5",
    card: "#ffffff",
    cardForeground: "#3F51B5",
    primary: "#7e6ee6",
    primaryForeground: "#ffffff",
    secondary: "#f0efff",
    secondaryForeground: "#3F51B5",
    muted: "#e7e8fb",
    mutedForeground: "#7680b8",
    accent: "#a4b1ff",
    accentForeground: "#3F51B5",
    destructive: "#e05f8f",
    destructiveForeground: "#ffffff",
    border: "#d0d4f7",
    input: "#f0efff",
    nexusGlow: "#a78bfa",
    updateGlow: "#a4b1ff",
    statusRead: "#7e6ee6",
    statusReading: "#3F51B5",
    statusUnread: "#9aa3cc",
    shelfColor: "#7e6ee6",
    shelfHighlight: "#c7cdfd",
  },
};

export const THEME_META: Record<ThemeId, { name: string; label: string; isDark: boolean }> = {
  default: { name: "default", label: "Dark Mode", isDark: true },
  botanical: { name: "botanical", label: "Botanical Library", isDark: false },
  cloudscape: { name: "cloudscape", label: "Oidenu Cloudscape", isDark: false },
  shire: { name: "shire", label: "Shire Sanctum", isDark: true },
  blush: { name: "blush", label: "Serene Blush Study", isDark: false },
  origami: { name: "origami", label: "Whimsical Origami", isDark: false },
  viking: { name: "viking", label: "Viking Berk", isDark: true },
  lavender: { name: "lavender", label: "Lavender Phantasm", isDark: false },
};
